#!/bin/bash

## Removes images,containers and networks related to devEnv script.
## To remove all dangling images, uncomment last line. It is not uncommented by default for you not lose important images.
docker-compose -f ../.docker/docker-compose.dev.yml -p vuejsapp down -v
docker image rm vuejsapp-app:latest
#docker image prune -a
