#!/bin/bash

docker-compose -f ../.docker/docker-compose.dev.yml -p vuejsapp up --force-recreate --build -d
docker inspect --format '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' vuejsDev 
