# Dockerfile for building the Vue.js documentation application
FROM node:18 AS build

# Set the working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application code
COPY . .
EXPOSE 4000
# Build the Hexo site
CMD npm run dev 

